### ISSUE TITLE
Artifacts after screen wakes up from sleep

### ISSUE THREAD

**Issue by Vivallo04** [archcraft-os/archcraft#276]
# Prerequisites

# Detailed Description

Whenever my screen blanks due to inactivity, once it wakes up again some artifacts are shown on the screen (mainly the desktop). 

# Expected Behavior
No artifacts shown after the screen wakes up from sleep. 

# Current Behavior
Artifacts after the screen goes blank or pc has been unlocked. 

## Steps to Reproduce

1. Wait the set time until your screen blanks after some period. 
2. Move the mouse to wake up the PC.
3. Artifacts will be shown on the desktop.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* ISO Version:  archcraft-2022.04.07-x86_64
* System Specs: Ryzen 5 3600. 
* Graphics Card: AMD 5600 XT

## Note: Attached is an image that shows the artifacts, it only affects the desktop, not any other windows that are on top of it. 
![Screenshot_2022-05-14-17-20-09_1920x1080 (copy 1)](https://user-images.githubusercontent.com/62166687/168451329-59b39c90-91cf-4c70-8683-8d3173a94a01.png)

**Comment by adi1090x** [comment]
Yes, It happens because of picom, I'm also facing this issue and thinking of replacing the picom fork with official picom.

BTW, this can easily fixed by restarting picom.

**Comment by riquezjp** [comment]
@adi1090x  This is still a problem with Archcraft. It spoils my enjoyment of the system often & makes it impossible to use as a daily. Id like to see this issue gain some priority. Is there any hope to fix?

**Comment by riquezjp** [comment]
@adi1090x  Any news on this, Im still facing it daily with new 2023 ISO. I tried the 20-amdgpu.conf fix, but no luck.
Perhaps this issue should be left open since it's ongoing?
